### ISSUE TITLE
{z}/{x}/{y}.png の目録エントリが発生する

### ISSUE THREAD

**Issue by hfu** [gsi-cyberjapan/tum#14]
## 概要

３月３０日２時１９分付けの /xyz/std/mokuroku.csv.gz には、 "{z}/{x}/{y}.png" の目録エントリが入っています。この目録を qdltc.rb にかけると、"{z}/{x}/{y}.png" がダウンロードできないままプログラムが終了しない症状となります。致命的な問題ではありませんが、次の機会に "{z}/{x}/{y}.png" が目録に加わらないよう tum を修正されるのも一案かと思います。
※この目録が tum によるものであるか、当方では検証はしていません。

すぐ修正することが難しい場合、（美しい手ではありませんが）qdltc.rb の側で対処することも検討可能と思います。
## 症状の詳細

３月３０日２時１９分付けの /xyz/std/mokuroku.csv.gz （全行数 5076万9617）の76万9617行目に、次のエントリが入っています。

```
{z}/{x}/{y}.png,1459157325000,2772,0bf10793eb58a94f6a174c39001d98fc
```
## 確認作業ログ

``` zsh
$ gzcat mokuroku.csv.gz | nl | grep "{z}"
769617  {z}/{x}/{y}.png,1459157325000,2772,0bf10793eb58a94f6a174c39001d98fc
$ gzcat mokuroku.csv.gz | wc -l
 50769617
$ ls -lh mokuroku.csv.gz
-rw-r--r--  1 hfu  staff   1.2G  3 30 02:19 mokuroku.csv.gz
```

**Comment by johofukyu** [comment]
報告いただいた症状について、当面はqdltc.rb側での対処とさせてください。
また現在作成されているmokuroku.csv.gzについて下記の症状が出ており、修正対応中です。
・２カラム目の最終更新時刻がエポックミリ秒形式で出力されている→エポック秒形式に修正
・改行コードが\r\nになっている。→\nに修正

**Comment by hfu** [comment]
qdltc 側でのスキップ処置を確認しました！ありがとうございました！
https://github.com/gsi-cyberjapan/qdltc/blob/gh-pages/qdltc.rb
